apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-business-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-business-app
  template:
    metadata:
      labels:
        app: my-business-app
    spec:
      containers:
      - name: my-business-app
        image: myacr.azurecr.io/my-business-app:latest
        ports:
        - containerPort: 80